name: venda_sys
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  bloc_pattern: ^3.0.0
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.3
  excel_to_json: ^0.0.1-dev.1
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
