name: venda_sys
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc_pattern: ^3.0.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
