name: venda_sys
description: A new Flutter project.

publish_to: 'none'

version: 0.1.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc_pattern: ^3.0.0
  cloud_firestore: ^2.5.4
  excel_to_json: ^0.0.1-dev.1
  file_picker: ^4.1.6
  firebase_auth: ^3.1.4
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  xml2json: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
