name: venda_sys
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  bloc_pattern: ^3.0.0+1
  brasil_fields: ^1.4.5
  cloud_firestore: ^3.1.15
  cloud_firestore_platform_interface: ^5.5.6
  excel_to_json: ^0.0.2-dev.1
  file_picker: ^4.5.1
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  url_strategy: ^0.2.0
  validators: ^3.0.0
  xml2json: ^5.3.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
