name: venda_sys
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  brasil_fields: ^1.4.5
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  translations_loader: ^1.0.2
  validators: ^3.0.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locale/
